version: '2'

services:

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  augslink:
    image: ukaj808/augs.link:latest
    ports:
      - "8080:8080"
    environment:
      - VIRTUAL_HOST=augs.link
      - VIRTUAL_PORT=8080