name: Deploy to Remote Host

on:
  push:
    branches:
      - master  # Trigger the workflow on pushes to the master branch

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Make working directory
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            mkdir -p /opt/augslink

      - name: Install ghcup (always update too)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            echo "Upating apt-get"
            apt-get update -y
            echo "Installing GHCUP dependencies"
            apt-get install -y build-essential curl libffi-dev libffi7 libgmp-dev libgmp10 libncurses-dev libncurses5 libtinfo5
            echo "Installing making temporary directory for GHCUP"
            mkdir /opt/augslink/ghcup-tmp
            echo "Exporting TMPDIR for ghcup memory issue"
            export TMPDIR="/opt/augslink/ghcup-tmp"
            echo $TMPDIR
            curl https://get-ghcup.haskell.org -sSf | sh
            echo "Removing ghcup temporary directory"
            rm -rf /opt/augslink/ghcup-tmp
            ghcup upgrade
            ghcup --version
    
      
      - name: Install GHC 9.2.7
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            ghcup install ghc 9.2.7
            ghcup set ghc 9.2.7
            ghc --version
      
      - name: Install Cabal (latest)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            ghcup install cabal
            cabal --version
      
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy source code to host
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: ./
          target: /opt/augslink/augslink
